### ISSUE TITLE
ibis installation error

### ISSUE THREAD

**Issue by ymeili** [williamslab/crest#3]
Hi, I was trying to use your crest method, however when I install ibis , it shows the error below:
g++ -MMD -std=c++2a -I. -Wall  -fopenmp -mpopcnt -O3 -o IBIS.o -c IBIS.cc
g++: error：unrecognized command line option ‘-std=c++2a’
make: *** [IBIS.o] error1

It seems the gcc version is too low, and then I upload gcc by conda, including gcc8,gcc9,gcc10 and gcc12. the error still exist. what should I do to solve this problem? Thanks a lot!

**Comment by DanielSeidman** [comment]
I think this was answered on general bioinformatics forums, but for future people who may encounter this issue:
https://www.biostars.org/p/9562548/#9562596
